# Generated by Django 4.1.7 on 2023-03-06 10:04

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('image', thumbnails.fields.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('get_thumbnails', thumbnails.fields.ImageField(upload_to='')),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('address', models.CharField(max_length=255)),
                ('year', models.DateField(default=datetime.date(2023, 3, 6))),
                ('position', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
            options={
                'verbose_name': 'Chairman Model',
                'verbose_name_plural': 'Chairman',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Position Model',
                'verbose_name_plural': 'Position',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Predisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('image', thumbnails.fields.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('get_thumbnails', thumbnails.fields.ImageField(upload_to='')),
                ('country', django_countries.fields.CountryField(default='UZB', max_length=2)),
                ('description', ckeditor.fields.RichTextField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Predisition Model',
                'verbose_name_plural': 'Predisition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('resume', models.FileField(upload_to='resume/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Resume Model',
                'verbose_name_plural': 'Resume',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=6, default=0, max_digits=6)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('days_work', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], default='full_time', max_length=25)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('file', models.FileField(upload_to='files/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Volunteer Model',
                'verbose_name_plural': 'Volunteer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.resume')),
                ('vacancy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.vacancy')),
            ],
            options={
                'verbose_name': 'User Resume Model',
                'verbose_name_plural': 'User Resume',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.vacancy'),
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('image', thumbnails.fields.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('get_thumbnails', thumbnails.fields.ImageField(upload_to='')),
                ('days', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='about.position')),
            ],
            options={
                'verbose_name': 'Management Model',
                'verbose_name_plural': 'Management',
                'ordering': ['-created_at'],
            },
        ),
    ]
