# Generated by Django 4.1.7 on 2023-03-07 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='year',
            field=models.DateField(default=datetime.date(2023, 3, 7)),
        ),
    ]
