# Generated by Django 4.1.7 on 2023-03-07 08:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('sum', models.DecimalField(decimal_places=6, max_digits=6)),
                ('payment_type', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('oson', 'Oson')], default='payme', max_length=25)),
            ],
            options={
                'verbose_name': 'Donate Model',
                'verbose_name_plural': 'Donate',
            },
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ImageField(upload_to='media/posts/')),
                ('url_address', models.URLField()),
            ],
            options={
                'verbose_name': 'InstagramPost Model',
                'verbose_name_plural': 'InstagramPost',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Location Model',
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.CreateModel(
            name='UseFulLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
