# Generated by Django 4.1.7 on 2023-03-06 11:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='docs/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('image', thumbnails.fields.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('get_thumbnails', thumbnails.fields.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', thumbnails.fields.ImageField(upload_to='icons/%Y/%m/%d/')),
                ('title', models.CharField(max_length=255)),
                ('image', thumbnails.fields.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('get_thumbnails', thumbnails.fields.ImageField(upload_to='')),
                ('description', ckeditor.fields.RichTextField()),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.document')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.member')),
            ],
            options={
                'verbose_name': 'Project Model',
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', ckeditor.fields.RichTextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.projects')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
